version: '3.7'
services:
  postgresdb:
    image: postgres
    container_name: postgresdb
    ports:
      - 5435:5432
    environment:
      - POSTGRES_PASSWORD=passwd
      - POSTGRES_DB=todo
    volumes:
      - postgres-data:/var/lib/postgresql/data
  todo-app:
    image: qwasolucoes/todo-app:latest
    environment:
      - spring.datasource.url=jdbc:postgresql://postgresdb/todo
      - spring.datasource.username=postgres
      - spring.datasource.password=passwd
    ports:
      - 8080:8080
    depends_on:
      - postgresdb
volumes:
  postgres-data: